version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: gestionpapier
    ports:
      - "3308:3306"
    networks:
      - app-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet_sem
    depends_on:
      - mysql
    ports:
      - "8092:8092"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge